version: '3.1'
services:
  app:
    container_name: datastorage
    image: springbootbackend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/news_storage
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=news_storage